services:

  prod-web:
    image: ghcr.io/jacob-grahn/platform-racing-4-client-web:${CLIENT_WEB_TAG}
    restart: always
  
  prod-api:
    image: ghcr.io/jacob-grahn/platform-racing-4-api:${API_TAG}
    restart: always
    volumes:
      - prod-api-data:/data
    environment:
      DB_PATH: data/pr4-api.db

volumes:
  prod-api-data:
    driver: local