services:

  pr4-web:
    container_name: pr4-web
    image: ghcr.io/jacob-grahn/platform-racing-4-client-web:${CLIENT_WEB_TAG}
    networks:
      - pr4-frontend
  
  pr4-api:
    container_name: pr4-api
    image: ghcr.io/jacob-grahn/platform-racing-4-api:${API_TAG}
    volumes:
      - pr4-api-data:/data
    environment:
      DB_PATH: data/pr4-api.db
    networks:
      - pr4-frontend

volumes:
  pr4-api-data:
    driver: local

networks:
  pr4-frontend:
    name: pr4-frontend
  pr4-backend:
    name: pr4-backend