services:
  caddy:
    restart: always
    volumes:
      - caddy-data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
    image: caddy:2.8-alpine
    ports:
      - 443:443
      - 443:443/udp
    environment:
      CONFIG_VERSION: 1 # update this number for force caddy to restart and read new config
    networks:
      pr2-frontend

volumes:
  caddy-data: {}

networks:
  pr2-frontend:
    name: pr2-frontend
    external: true