services:

  pr4-dev-web:
    container_name: pr4-dev-web
    image: ghcr.io/jacob-grahn/platform-racing-4-client-web:${CLIENT_WEB_TAG}
    networks:
      - pr4-dev-frontend
  
  pr4-dev-api:
    container_name: pr4-dev-api
    image: ghcr.io/jacob-grahn/platform-racing-4-api:${API_TAG}
    volumes:
      - pr4-dev-api-data:/data
    environment:
      DB_PATH: data/pr4-dev-api.db
    networks:
      - pr4-dev-frontend

volumes:
  pr4-dev-api-data:
    driver: local

networks:
  pr4-dev-frontend:
    name: pr4-dev-frontend
  pr4-dev-backend:
    name: pr4-dev-backend