services:

  web:
    image: ghcr.io/jacob-grahn/platform-racing-4-client-web:${CLIENT_WEB_TAG}
    networks:
      - pr4-dev-frontend:
          aliases:
            - pr4-dev-web
  
  api:
    image: ghcr.io/jacob-grahn/platform-racing-4-api:${API_TAG}
    volumes:
      - api-data:/data
    environment:
      DB_PATH: data/pr4-api.db
    networks:
      - pr4-dev-frontend:
          aliases:
            - pr4-dev-api

volumes:
  api-data:
    driver: local

networks:
  pr4-dev-frontend:
    name: pr4-dev-frontend
  pr4-dev-backend:
    name: pr4-dev-backend