services:

  cadvisor:
    container_name: monitoring-cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    platform: linux/amd64/v3
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg:/dev/kmsg
    privileged: true
    networks:
      - monitoring-backend

  prometheus:
    container_name: monitoring-prometheus
    image: prom/prometheus:v2.53.2
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    environment:
      config_version: 3 # increment to force new config change to load
    volumes:
      - ./prometheus-config.yml:/etc/prometheus.yaml
      - prometheus-data:/prometheus
    networks:
      - monitoring-backend
      - pr2-backend
    ports:
      - 9090:9090
  
  loki:
    container_name: monitoring-loki
    image: grafana/loki:3.1.1
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
    networks:
      - monitoring-backend

  grafana:
    container_name: monitoring-grafana
    image: grafana/grafana-oss:11.1.3
    volumes:
      - ./grafana-config.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      GF_FEATURE_TOGGLES_ENABLE: traceqlEditor traceQLStreaming metricsSummary
    networks:
      - monitoring-frontend
      - monitoring-backend
  
  tempo:
    container_name: monitoring-tempo
    image: grafana/tempo:2.5.0
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo-config.yaml:/etc/tempo.yaml
      - tempo-data:/var/tempo
    #ports:
      #- "14268:14268"  # jaeger ingest
      #- "3200:3200"   # tempo
      #- "9095:9095" # tempo grpc
      #- "4317:4317"  # otlp grpc
      #- "4318:4318"  # otlp http
      #- "9411:9411"   # zipkin
    networks:
      - monitoring-backend
  
volumes:
  grafana-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/grafana-data
  loki-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/loki-data
  prometheus-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/prometheus-data
  tempo-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/tempo-data

networks:
  monitoring-frontend:
    name: monitoring-frontend
  monitoring-backend:
    name: monitoring-backend
  pr2-backend:
    name: pr2-backend
    external: true
