services:

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    platform: linux/amd64/v3
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg:/dev/kmsg
    privileged: true
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.53.2
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    volumes:
      - ./prometheus-config.yml:/etc/prometheus.yml
      - prometheus-data:/prometheus
    restart: unless-stopped
  
  loki:
    image: grafana/loki:3.1.1
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:11.1.3
    volumes:
      - ./grafana-config.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor traceQLStreaming metricsSummary
    restart: unless-stopped
  
  tempo:
    image: grafana/tempo:2.5.0
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo-config.yaml:/etc/tempo.yaml
      - tempo-data:/var/tempo
    ports:
      #- "14268:14268"  # jaeger ingest
      #- "3200:3200"   # tempo
      #- "9095:9095" # tempo grpc
      #- "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http
      #- "9411:9411"   # zipkin
  
volumes:
  grafana-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/grafana-data
  loki-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/loki-data
  prometheus-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/prometheus-data
  tempo-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/tempo-data
