services:

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    platform: linux/amd64/v3
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg:/dev/kmsg
    privileged: true

  prometheus:
    image: prom/prometheus:v2.53.2
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  
  loki:
    image: grafana/loki:3.1.1
    ports:
      - "3100:3100"
  
  grafana:
    image: grafana/grafana-oss:11.1.3
    volumes:
      - grafana-data:/var/lib/grafana
      - ./datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
  
volumes:
  grafana-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/grafana-data
