services:
  caddy:
    container_name: ingress-caddy
    image: iarekylew00t/caddy-cloudflare:2.8
    volumes:
      - caddy-data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 443:443
      - 443:443/udp
    environment:
      CONFIG_VERSION: 17 # update this number for force caddy to restart and read new config
    networks:
      - pr4-dev-frontend
      - pr4-frontend
      - br-frontend
      - monitoring-frontend
      - pr2-frontend

volumes:
  caddy-data: {}

networks:
  pr4-dev-frontend:
    name: pr4-dev-frontend
    external: true
  pr4-frontend:
    name: pr4-frontend
    external: true
  br-frontend:
    name: br-frontend
    external: true
  monitoring-frontend:
    name: monitoring-frontend
    external: true
  pr2-frontend:
    name: pr2-frontend
    external: true