services:
  db:
    image: mysql:9.0
    volumes:
      - db-data:/var/lib/mysql
      - db-backups:/backups
    networks:
      - backend

volumes:
  db-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/data/pr2-db-data'
  db-backups:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/backups/pr2-db-backups'

networks:
  frontend: {}
  backend: {}