services:

  pr2-mysql:
    container_name: pr2-mysql
    image: mysql:9.0
    volumes:
      - pr2-mysql-data:/var/lib/mysql
    networks:
      - pr2-backend
    ports:
      - 3306:3306 # note: keep the port firewalled from the public

  # exposes database metrics for prometheus
  pr2-mysql-exporter:
    container_name: pr2-mysql-exporter
    image: prom/mysqld-exporter:v0.15.1
    command: --mysqld.address=pr2-mysql:3306 --mysqld.username=exporter
    networks:
      - pr2-backend
    #ports:
    # - 9104:9104
  
  pr2-http:
    container_name: pr2-http
    image: ghcr.io/jacob-grahn/platform-racing-2-http:${HTTP_TAG}
    networks:
      - pr2-frontend
      - pr2-backend
  
  pr2-multi-1:
    image: ghcr.io/jacob-grahn/platform-racing-2-multi:${MULTI_TAG}
    environment:
      SERVER_ID: 1
    networks:
      - pr2-frontend
      - pr2-backend
    ports:
      - 9160:9160
  
  pr2-multi-2:
    image: ghcr.io/jacob-grahn/platform-racing-2-multi:${MULTI_TAG}
    environment:
      SERVER_ID: 2
    networks:
      - pr2-frontend
      - pr2-backend
    ports:
      - 9161:9161
  
  pr2-multi-3:
    image: ghcr.io/jacob-grahn/platform-racing-2-multi:${MULTI_TAG}
    environment:
      SERVER_ID: 3
    networks:
      - pr2-frontend
      - pr2-backend
    ports:
      - 9162:9162
  
  pr2-multi-4:
    image: ghcr.io/jacob-grahn/platform-racing-2-multi:${MULTI_TAG}
    environment:
      SERVER_ID: 4
    networks:
      - pr2-frontend
      - pr2-backend
    ports:
      - 9163:9163
  
  pr2-multi-11:
    image: ghcr.io/jacob-grahn/platform-racing-2-multi:${MULTI_TAG}
    environment:
      SERVER_ID: 11
    networks:
      - pr2-frontend
      - pr2-backend
    ports:
      - 9168:9168
  
  pr2-multi-12:
    image: ghcr.io/jacob-grahn/platform-racing-2-multi:${MULTI_TAG}
    environment:
      SERVER_ID: 12
    networks:
      - pr2-frontend
      - pr2-backend
    ports:
      - 9171:9171
  
  pr2-multi-13:
    image: ghcr.io/jacob-grahn/platform-racing-2-multi:${MULTI_TAG}
    environment:
      SERVER_ID: 13
    networks:
      - pr2-frontend
      - pr2-backend
    ports:
      - 9172:9172

volumes:
  pr2-mysql-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/pr2-mysql-data

networks:
  pr2-frontend:
    name: pr2-frontend
  pr2-backend:
    name: pr2-backend